GET http://localhost:4000/api/topics

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email":"lacey",
  "password":"lacey"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json


{
  "email":"carlos",
  "password":"carlos"
}

###

GET http://localhost:5000/api/topics
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJlbWFpbCI6ImNhcmxvcyIsImlhdCI6MTYxOTExMTM2NywiZXhwIjoxNjE5MTExMzgyfQ.-8aoJa5sDcGho_6jB0TN-rGo474MHwZxQVGeuvN5YsQ
###

POST http://localhost:5000/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJlbWFpbCI6ImNhcmxvcyIsImlhdCI6MTYxOTExMTM2N30.SEZGPh0hLqw0QI3DdcZQcn0_dd0Tpkn9lUuMxJBWl_I"
}

###

DELETE http://localhost:5000/logout
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJlbWFpbCI6ImNhcmxvcyIsImlhdCI6MTYxOTExMDU3MH0.ptGjhejeGcgFYwXGilX27gnTfTBgwVkihyyCsXbFKGk"
}
